### ISSUE TITLE
the examples doesn't work

### ISSUE THREAD

**Issue by MansourWolou** [fbsamples/whatsapp-api-examples#1]
on https://developers.facebook.com/ u config only one callback url. for me that means u can only use one endpoint to config your webhook. how did you config it ?

**Comment by dmitryvinn-fb** [comment]
@MansourWolou have you followed the steps outlined in [this blog post](https://business.whatsapp.com/blog/manage-message-templates-whatsapp-business-api)? This code accompanies the post so it should answer any questions you might have - please let us know if you are still blocked.
