### ISSUE TITLE
Profile and QR code issue

### ISSUE THREAD

**Issue by umerghayaz** [fbsamples/whatsapp-api-examples#2]
can u please provide  python method to get and  update WhatsApp api business profile and please also qr code sending option method in python.

**Comment by rashedtalukder** [comment]
Hi @umerghayaz, we don't currently have plans to rewrite all of our examples in Python but I'll keep your request in mind. We currently have this one example but doesn't update the business profile: https://github.com/fbsamples/whatsapp-api-examples/tree/main/send-messages-flight-app-python
