### ISSUE TITLE
Meta: CEASE AND DESIST

### ISSUE THREAD

**Issue by pboling** [fbsamples/whatsapp-api-examples#5]
For those who have access to GitHub's Maintainers Org for OSS devs, Meta may be one of the worst enemies OSS has.  Will there be healing or war?  You decide.

https://github.com/community/maintainers/discussions/341#discussioncomment-6493532

**Comment by rguan1** [comment]
Closing this issue, since I don't believe this is related to this repo. Also the link that you linked seems to be dead.
