### ISSUE TITLE
Whatsapp API messages templates from those examples: where ?

### ISSUE THREAD

**Issue by nicolasmol** [fbsamples/whatsapp-api-examples#6]
When I finally managed to create my first WhatsAppp application in this obstacles course that are the Meta backoffice pages (BTW, I have never seen such "thing" in terms of ergonomics that would make Steve Jobs turn in his grave, that is to say dispersing in myriads of different places on each page links to same pages and functionalities), I got only the "Hello World" template.

Nowhere in the documentation I was able to find where and how to get the others mentioned in those examples.

**Comment by rguan1** [comment]
Hey Nicolas, sorry for the late follow-up.

Is your question regarding finding the other templates referenced in the repo?

**Comment by rguan1** [comment]
Ok, I'm going to close out this task for now. Please re-open if you need a followup.
